from enum import Enum, auto


class OpCode(Enum):
    ACQUIRE = 0
    RELEASE = auto()

    ADD = auto()
    ADDC = auto()
    AND = auto()
    ANDN = auto()
    ASR = auto()
    CAO = auto()
    CLO = auto()
    CLS = auto()
    CLZ = auto()
    CMPB4 = auto()
    DIV_STEP = auto()
    EXTSB = auto()
    EXTSH = auto()
    EXTUB = auto()
    EXTUH = auto()
    LSL = auto()
    LSL_ADD = auto()
    LSL_SUB = auto()
    LSL1 = auto()
    LSL1X = auto()
    LSLX = auto()
    LSR = auto()
    LSR_ADD = auto()
    LSR1 = auto()
    LSR1X = auto()
    LSRX = auto()
    MUL_SH_SH = auto()
    MUL_SH_SL = auto()
    MUL_SH_UH = auto()
    MUL_SH_UL = auto()
    MUL_SL_SH = auto()
    MUL_SL_SL = auto()
    MUL_SL_UH = auto()
    MUL_SL_UL = auto()
    MUL_STEP = auto()
    MUL_UH_UH = auto()
    MUL_UH_UL = auto()
    MUL_UL_UH = auto()
    MUL_UL_UL = auto()
    NAND = auto()
    NOR = auto()
    NXOR = auto()
    OR = auto()
    ORN = auto()
    ROL = auto()
    ROL_ADD = auto()
    ROR = auto()
    RSUB = auto()
    RSUBC = auto()
    SUB = auto()
    SUBC = auto()
    XOR = auto()

    BOOT = auto()
    RESUME = auto()
    STOP = auto()

    CALL = auto()

    FAULT = auto()
    NOP = auto()
    SATS = auto()
    MOVD = auto()
    SWAPD = auto()

    HASH = auto()
    TIME = auto()
    TIME_CFG = auto()

    LBS = auto()
    LBU = auto()
    LD = auto()
    LHS = auto()
    LHU = auto()
    LW = auto()

    SB = auto()
    SB_ID = auto()
    SD = auto()
    SD_ID = auto()
    SH = auto()
    SH_ID = auto()
    SW = auto()
    SW_ID = auto()

    LDMA = auto()
    LDMAI = auto()
    SDMA = auto()
